import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  subsets: ['latin', 'vietnamese'],
  weight: ['200', '400', '700'],
  variable: '--font-oswald', // Khai báo biến ở đây
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${oswald.className} antialiased max-w-5xl mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
